# fly.toml app configuration file generated for portfolio-crimson-wind-4183 on 2024-06-22T17:43:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-crimson-wind-4183'
primary_region = 'mad'

[build]
[build.args]
 VITE_API_BASE_URL = "https://portfolio-crimson-wind-4183/api/v1"

[env]
  CORS_ORIGIN = "https://portfolio-crimson-wind-4183.fly.dev"



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
